rocq-community/manifesto

- CONTRIBUTING.md
We add a link to the list of "help wanted" issues to the contributing guide.
Note that "help wanted" issues are also highlighted by GitHub in the organization's list of repositories:
cc @spitters
> Contributing: add link to issues labelled 'help wanted'.

- templates/README.md.mustache
- templates/examples/aac-tactics/README.md
- templates/examples/aac-tactics/meta.yml
- templates/examples/aac-tactics/opam
- templates/examples/lemma-overloading/README.md
- templates/examples/lemma-overloading/meta.yml
Here is my proposal for modifying templates to allow non-initial authors to be credited in `README.md` and `opam`.
Fixes #29.
> allow both initial and other authors in README.md and opam templates

- templates/examples/aac-tactics/README.md
- templates/examples/aac-tactics/meta.yml
- templates/examples/aac-tactics/opam
- templates/examples/lemma-overloading/meta.yml
- templates/opam.mustache
Many packages in Coq's OPAM repo actually have several categories in their `opam` files. For example, the most recent version of `coq-color` has seven categories. Here are changes to support this in our templates.
> allow multiple categories in mustache opam template, update examples

- templates/examples/aac-tactics/meta.yml
- templates/examples/aac-tactics/opam
- templates/examples/lemma-overloading/README.md
- templates/examples/lemma-overloading/meta.yml
- templates/examples/lemma-overloading/opam
I updated the `meta.yml` files a bit for the examples. In particular, I noticed that the preferred form for licenses in OPAM files in the Coq OPAM repo includes a space between the acronym and the version (`LGPL 2.1` vs. `LGPL2.1`). I don't think we should override this convention.
> Update examples generated from templates

- templates/opam.mustache
According to the Coq OPAM archive spec, released packages should include a `date` attribute under the `tags` field to indicate when the release was made, e.g., `"date:2018-07-24"`. To introduce more automation, `meta.yml` can include a `date` variable that automatically introduces this into the `opam` file.
> add optional date to opam template

- templates/README.md.mustache
- templates/examples/aac-tactics/README.md
- templates/examples/aac-tactics/meta.yml
- templates/examples/lemma-overloading/README.md
- templates/examples/lemma-overloading/meta.yml
Lots of projects have at least one paper that describes them. For these projects, it makes sense to record metadata for both URL to access paper and DOI for paper (for citing). Here is optional support for having such a paper in the templates. Would make README maintenance easier.
> add support for paper metadata in templates

- templates/examples/aac-tactics/meta.yml
- templates/examples/aac-tactics/opam
- templates/examples/lemma-overloading/meta.yml
- templates/examples/lemma-overloading/opam
- templates/opam.mustache
Also, get rid of informal license string and move tags for category up top for easier reading.
> use SPDX license identifier in template opam file

- templates/README.md.mustache
> paper titles shouldn't be escaped in README.md template

- templates/README.md.mustache
- templates/examples/aac-tactics/.travis.yml
- templates/examples/aac-tactics/README.md
- templates/examples/aac-tactics/meta.yml
- templates/examples/aac-tactics/opam2
- templates/examples/lemma-overloading/.travis.yml
- templates/examples/lemma-overloading/README.md
- templates/examples/lemma-overloading/meta.yml
- templates/examples/lemma-overloading/opam2
- templates/opam2.mustache
This is a (possibly-controversial?) PR where I both generalize some templates to also accommodate coq-contrib projects, and introduce an OPAM 2 template.
cc: @Zimmi48 @herbelin
> generalize templates to also fit coq-contrib, introduce opam2 template

- templates/README.md.mustache
- templates/opam.mustache
- templates/opam2.mustache
We can store emails from legacy description files for authors in `email` entries in `meta.yml`:
```
authors:
- name: James R. Hacker
initial: true
email: jrh@example.com
```
These then get reflected in `opam` files using this template modification.
> show email in opam when available, fix more escaping

- templates/examples/aac-tactics/.travis.yml
- templates/examples/aac-tactics/meta.yml
- templates/examples/lemma-overloading/.travis.yml
- templates/examples/lemma-overloading/meta.yml
The coq-on-cachix repo lags a bit behind the main Coq repo but guarantees that it has already been built and uploaded to Cachix.
See also https://github.com/coq/coq/wiki/Nix.
> Update CI template examples to use the new coq-on-cachix repo.

- templates/README.md.mustache
- templates/examples/aac-tactics/README.md
- templates/examples/aac-tactics/meta.yml
- templates/examples/lemma-overloading/README.md
- templates/examples/lemma-overloading/meta.yml
While I agree with the criticism by @Zimmi48 in #44, I feel the burden of having separate README templates for coq-community and coq-contribs will be high. I was also hoping to use the template for other Coq projects.
Here is a compromise where a variable `community` can be used to add the community-specific parts. Here is what the adjusted README looks like on a coq-contrib project: https://github.com/palmskog/quicksort-complexity/tree/meta
> Variable to make badges/maintainers optional in README

- templates/coq.opam.mustache
- templates/examples/aac-tactics/coq-aac-tactics.opam
- templates/examples/chapar/coq-chapar.opam
- templates/examples/lemma-overloading/coq-lemma-overloading.opam
The Coq OPAM archive maintainers now require that there are no `remove` clauses in OPAM files, since OPAM 2 handles tracking of installed files. Here is an update to our template to reflect this.
> use automatic uninstall in OPAM files

- templates/.travis.yml.mustache
- templates/examples/aac-tactics/.travis.yml
- templates/examples/chapar/.travis.yml
- templates/examples/lemma-overloading/.travis.yml
I've seen some weird behavior from unqualified `opam pin add [...] .`, i.e., when pinning the current directory. This change ensures that local directories are always used in Travis.
> add '-k path' option to opam in travis to avoid remote packages in CI

- CODE_OF_CONDUCT.md
The link was broken because of this typo.
> Fix typo in CODE_OF_CONDUCT.md.

- README.md
Step toward coq-community/templates#40.
> Move badge from Gitter to Zulip.

- CODE_OF_CONDUCT.md
I want to ensure that coq-community members are not attacked or reported for code-of-conduct violations based on (possibly politically-charged) statements or behavior that occur **outside** of coq-community, e.g., on Twitter, in personal blogs, and in issues in other GitHub organizations. 
Here are two refinements of the code of conduct which I believe are conducive to this goal.
Note that the explicit mention of political views as an aspect of personal identity also exist in the Julia community standards, which the current code is based on.
> Refine code of conduct

- README.md
For reasons which I've explained elsewhere (cf. https://github.com/coq-community/templates/issues/34#issuecomment-634565291 and https://github.com/coq-community/corn/pull/99#issuecomment-667997810), I believe that we should encourage the Coq community in general, and the coq-community projects in particular, to adopt more permissive licenses and to move away from LGPL (at least for new projects). This FAQ item in the manifesto's README should be a step in this direction.
> Add an FAQ on choice of licenses.

- CONTRIBUTING.md
- README.md
- Link to Hydra Battles and cie (cc @Casteran).
- No more editorial board (didn't materialize).
- Reorganize and extend FAQ (new questions pointing to the contributing guide).
- Fix links to issue templates in the contributing guide.
> Update manifesto with current state of affairs.

- CONTRIBUTING.md
- README.md
We want to explicitly allow non-OSI free software licenses such as CECILL-B and CECILL-C, while encouraging MIT/MPL-2.0 and preferring OSI over non-OSI. Based on [this discussion in the Coq Zulip](https://coq.gitlab.io/zulip-archive/stream/237663-coq-community-devs-&-users/topic/open.20source.20vs.2E.20OSI.html).
I change from "choose" to "use", since these are requirements that restrict choice rather than mere recommendations on top of free choice.
> restrict licenses to OSI approved or FSF free software, encourage OSI-FSF intersection

- README.md
Followup to comment by @Zimmi48 in #93.
> add FAQ item on Coq's CI

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE.md
- README.md
This is a conservative initial pass at renaming Coq to Rocq in `.md` files. I suggest merging this quickly and doing a followup PR when the `coq` GitHub organization is renamed.
> Renaming Coq to Rocq
